### ISSUE TITLE
Flow 7 compatibility

### ISSUE THREAD

**Issue by PRGfx** [digital-competence/FlowSessionLock#1] opened 2022-06-14 10:16 UTC
This package seems to have resolved issues for us, so we intended to keep using it.
Has it been tested with flow 7 or 8 yet or is it no longer necessary in current versions of the framework?

**Comment by fcool** [comment] 2022-06-14 10:19
Sadly its still needed with Flow 7. 

An updated version will be released the next days.

And hopefully it won't be necessary for 8.1 ongoing, but at least in the current 8.0 the issue is still existing. It's not that easy to fix it at the Framework level without breakage.

We will maintain this package as long as the problem in the Flow core persists.

**Comment by fcool** [comment] 2022-06-14 10:21
(Let me know, if you need it "this day". I have already a version, which is working with Flow 7, but to get the functional tests running, there is a pending patch request for Flow - but the Package itself already works)

**Comment by PRGfx** [comment] 2022-06-14 10:33
Thank you so much. We were planning an upgrade for the coming weeks, so we can wait for the release.

**Comment by fcool** [comment] 2022-07-31 22:41
The develop branch is now Flow 7.3 compatible. It will be finally released as soon as the next flow versions get released. This should be the moment, where the fresh functional tests should work (as another bug in flow currently breaks the measurement, functionality already fully works and there are - apart from testing - no breakages known.)

But apart from the test this version will be veeeeery probably the final - at least I do not expect any breaking changes.

Release version will be 3.0.0

**Comment by fcool** [comment] 2022-08-30 12:49
Version 3.0.0 released today. Functional tests work - as expected with the release of flow today.

**Closed as completed by fcool** 2022-08-30 12:49 UTC
